version: '3.2'

services:
  # If you want to use a MySQL database, provided by Docker, uncomment below:
  # db:
  #   image: mysql
  #   environment:
  #     MYSQL_RANDOM_ROOT_PASSWORD: yes
  #     MYSQL_DATABASE: mediawiki
  #     MYSQL_USER: mediawiki
  #     MYSQL_PASSWORD: password

  # If you want to use a Postgres database, provided by Docker, uncomment below:
  # db:
  #   image: postgres
  #   environment:
  #     POSTGRES_DB: mediawiki
  #     POSTGRES_USER: mediawiki
  #     POSTGRES_PASSWORD: password

  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # you can specify a mediawiki version using the 'MEDIAWIKI_VERSION' arg
        MEDIAWIKI_VERSION: 1.27.4
    ports:
      - 80:80
      # - 443:443
    # use the links section if you want to use a container for a database.
    # if not, and you want to use an external database server, configure
    # if with the environment variables in the 'environment' section.
    # see README.md for more details.
    links:
      - db
    depends_on:
      - db
    # uncomment the 'volumes' section to retain uploads
    # volumes:
    #   - /local/data/dir:/data:rw
    environment:
      MEDIAWIKI_SITE_SERVER: //my-wiki
      MEDIAWIKI_SITE_NAME: My Awesome Wiki

      # you need to specify the reference to the database, Docker no longer
      # shares environmental variables between linked containers
      MEDIAWIKI_DB_TYPE: mysql # 'mysql' or 'postgres'
      MEDIAWIKI_DB_HOST: db
      MEDIAWIKI_DB_USER: mediawiki
      MEDIAWIKI_DB_PASSWORD: password
      MEDIAWIKI_DB_NAME: mediawiki

      # uncomment 'MEDIAWIKI_ENABLE_SSL' to enable SSL support
      # MEDIAWIKI_ENABLE_SSL: true
